Client certificate
chaintope/tapyrus-api-client-examples pull request #10
Opened 2022-07-25 04:56 UTC by Yamaguchi

Sample code to use client certificates.

2022-10-11 08:26 UTC, rantan requested changes
GettingStarted-ja.md も更新が必要です。

2022-10-12 01:17 UTC, rantan commented
@Yamaguchi 認証を試みたときに、以下のエラーで失敗します。なにか心当たりありますか？
```
$ node index.js 
Example app listening at http://localhost:3000
node:internal/tls/secure-context:277
      context.loadPKCS12(toBuf(pfx), toBuf(passphrase));
              ^

Error: unsupported
    at configSecureContext (node:internal/tls/secure-context:277:15)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Object.connect (node:_tls_wrap:1629:48)
    at Agent.createConnection (node:https:150:22)
    at Agent.createSocket (node:_http_agent:350:26)
    at Agent.addRequest (node:_http_agent:297:10)
    at new ClientRequest (node:_http_client:335:16)
    at Object.request (node:https:360:10)
    at internals.Client._request (/home/rantan/repos/chaintope/tapyrus-api-client-examples/javascript/example-app/node_modules/@hapi/wreck/lib/index.js:181:28)
    at internals.Client.request (/home/rantan/repos/chaintope/tapyrus-api-client-examples/javascript/example-app/node_modules/@hapi/wreck/lib/index.js:75:26)

Node.js v18.10.0
```

2022-10-12 01:41 UTC, rantan commented
現在クライアント証明書で使用しているアルゴリズムが古く OpenSSL 3 では無効になっているようです。node 17 からは openssl 3 へ移行しており、その影響でこのエラーが出ているようです。

```
$ openssl pkcs12 -info -in user.p12 -noout
Enter Import Password:
MAC: sha1, Iteration 1
MAC length: 20, salt length: 8
PKCS7 Encrypted data: pbeWithSHA1And40BitRC2-CBC, Iteration 2048
Certificate bag
PKCS7 Data
Shrouded Keybag: pbeWithSHA1And3-KeyTripleDES-CBC, Iteration 2048
```

参考: https://github.com/nodejs/node/issues/40672#issuecomment-955856334

2022-10-12 01:46 UTC, rantan commented
以下のように起動することで、エラーを回避し、認証に成功しました。

```
$ node --openssl-legacy-provider index.js 
```

ただし、クライアント証明書に利用しているアルゴリズムの見直しは必要ですね。

2022-10-12 05:36 UTC, rantan commented
アルゴリズムの見直しについては Issue にしました。
https://github.com/chaintope/tapyrus-api-dashboard/issues/190

2022-10-24 17:56 UTC, Yamaguchi commented
> GettingStarted-ja.md も更新が必要です。

6b1c1b8912202e4d57c7f4c3edba1539dd040e76で変更しました。

2022-11-07 08:30 UTC, rantan requested changes

2022-11-07 08:30 UTC, rantan commented on javascript/GettingStarted-ja.md
この時点では 認証は成功しないので、02.png のように 「Hello, World!」とは表示されないと思います。
クライアント証明書の記述まで先に入れてしまって、認証が通るところまで進めてから tapyrus API の実際のAPIを叩くところに進んだ方が良いと思いますがいかがでしょうか？

2022-11-07 08:30 UTC, rantan commented on javascript/GettingStarted-ja.md
> +### 4.1. tapyrus_api NPM パッケージの追加
Tapyrus API の URL に 'https://testnet-api.tapyrus.chaintope.com/api/v1' を使うようになっていますが、ダッシュボードで実際の利用者の API エンドポイントを確認してここで使うような進行にした方が良いと思いました。
そうしないと実際に接続できないので。

2022-11-07 08:30 UTC, rantan commented on javascript/GettingStarted-ja.md
> +ブラウザから使用するクライアント証明書が求められますので、インストールしたクライアント証明書を選択して、処理を続行します。
node v17 以降では以下のオプションが必要であることを記載した方が良いと思います。
```
$ node  --openssl-legacy-provider index.js
```

2022-11-07 08:30 UTC, rantan commented on javascript/GettingStarted-ja.md
> +変数 `config` を宣言している部分を以下のように変更します。
```suggestion
変数 `config` を宣言している部分を以下のように変更します。証明書のダウンロード時にパスワードを設定しなかった場合は、`passphrase = '';` としてください。
```

2022-11-07 08:30 UTC, rantan commented on javascript/GettingStarted-ja.md
> +const passphrase = 'クライアント証明書のパスワード'
```suggestion
const cert = 'クライアント証明書ファイル名(p12)';
const passphrase = 'クライアント証明書のパスワード';
```

2022-11-07 08:30 UTC, rantan commented on javascript/GettingStarted-ja.md
> +const tapyrusApiHost = 'https://testnet-api.tapyrus.chaintope.com';
```suggestion
const tapyrusApiHost = 'ダッシュボードから実際のエンドポイントのURLを入手して置き換えてください';
```

2022-11-07 08:30 UTC, rantan commented on javascript/GettingStarted-ja.md
>  `basePath` に設定するのは利用する Tapyrus API のエンドポイントです。 ここでは testnet を利用する想定ですが、別のチェーンを使う場合は、それに合わせた Tapyrus API
クライアントライブラリの初期化は以下のような感じでどうでしょうか？
８章で宣言している tapyrusApiHost  を最初から宣言しておいた方が良いと思いました。

```javascript
const tapyrusApiHost = 'ダッシュボードから実際のエンドポイントのURLを入手して置き換えてください';
const TapyrusApi = require('tapyrus_api');
const defaultClient = TapyrusApi.ApiClient.instance;
defaultClient.basePath = `${tapyrusApiHost}/api/v1`;
```

2022-11-10 17:32 UTC, Yamaguchi commented on javascript/GettingStarted-ja.md
章立てを
OIDCの設定=>クライアント証明書の設定=>APIの呼び出し
の順に変更しました。

2022-11-10 17:34 UTC, Yamaguchi commented on javascript/GettingStarted-ja.md
> +const tapyrusApiHost = 'https://testnet-api.tapyrus.chaintope.com';
0bf2d5849bbee37da951c3d740c544dc029c25f9 で修正しました。

2022-11-10 17:34 UTC, Yamaguchi commented on javascript/GettingStarted-ja.md
> +const passphrase = 'クライアント証明書のパスワード'
0bf2d5849bbee37da951c3d740c544dc029c25f9 で修正しました。

2022-11-10 17:34 UTC, Yamaguchi commented on javascript/GettingStarted-ja.md
> +変数 `config` を宣言している部分を以下のように変更します。
0bf2d5849bbee37da951c3d740c544dc029c25f9 で追記してます。

2022-11-10 17:34 UTC, Yamaguchi commented on javascript/GettingStarted-ja.md
> +ブラウザから使用するクライアント証明書が求められますので、インストールしたクライアント証明書を選択して、処理を続行します。
0bf2d5849bbee37da951c3d740c544dc029c25f9 で追記してます。

2022-11-10 17:34 UTC, Yamaguchi commented on javascript/GettingStarted-ja.md
> +### 4.1. tapyrus_api NPM パッケージの追加
0bf2d5849bbee37da951c3d740c544dc029c25f9 で修正しました。

2022-11-10 17:35 UTC, Yamaguchi commented on javascript/GettingStarted-ja.md
>  `basePath` に設定するのは利用する Tapyrus API のエンドポイントです。 ここでは testnet を利用する想定ですが、別のチェーンを使う場合は、それに合わせた Tapyrus API
0bf2d5849bbee37da951c3d740c544dc029c25f9 で修正しました。

2022-11-14 05:43 UTC, rantan requested changes
「このドキュメントのゴール」にある以下の2項目は消した方が良いと思います。１つ目は今は不要な操作ですし、２つ目は、Tapyrus API Mainnet ではエクスプローラー環境を用意していないので達成できませんし。

* Tapyrus API ユーザーのウォレットに TPC を供給して、トランザクションを発行する API の準備の方法を理解する。
* Tapyrus API で行った操作によって作られたトランザクションをエクスプローラーで確認する方法を理解する。

「対象とするブロックチェーン」の部分は、利用する Tapyrus API endpoint に依存するため、このドキュメントからは除外してよいと思います。

ちょっと PR の趣旨からずれてきますが、TPC の送金 API は今は使えないので、この Example の構成も token の発行・送金をする形にするなど変更が必要ですね。。

2022-11-14 05:43 UTC, rantan commented on javascript/GettingStarted-ja.md
> +今回はテストネットを例に使っていますので、テストネットのfaucetからコインを入手します。 テストネット以外のネットワークを利用する場合は、その Tapyrus チェーンを運営しているフェデレーションの案内を確認してください。
見逃していましたが、Tapyrus API を使うにあたって faucet からの TPC の入手は不要ですね。

2022-11-22 07:17 UTC, merged