Add Getting Started document for javascript client
chaintope/tapyrus-api-client-examples pull request #8
Opened 2021-07-14 02:37 UTC by rantan

2021-07-15 04:57 UTC, Yamaguchi commented on javascript/example-app/index.js
> +let oidc_client;
"oidc_client"だけsnake_caseなのは理由ありですか

2021-07-15 05:08 UTC, Yamaguchi requested changes

2021-07-15 05:08 UTC, Yamaguchi commented on javascript/example-app/package.json
> +    "tapyrus_api": "file:../../../tapyrus-api/out/tapyrus-api-client-js"
Use published version

2021-07-15 07:15 UTC, rantan commented on javascript/example-app/index.js
> +let oidc_client;
特に理由はないです。Camel case に修正します

2021-07-15 07:15 UTC, rantan commented on javascript/example-app/package.json
> +    "tapyrus_api": "file:../../../tapyrus-api/out/tapyrus-api-client-js"
治すのを忘れていました。。ありがとうございます。

2021-07-19 08:30 UTC, rantan commented on javascript/example-app/index.js
> +let oidc_client;
修正しました。

2021-07-19 08:30 UTC, rantan commented on javascript/example-app/package.json
> +    "tapyrus_api": "file:../../../tapyrus-api/out/tapyrus-api-client-js"
修正しました。

2021-07-28 11:51 UTC, Yamaguchi requested changes
6. TPCを入手するあたりまで

2021-07-28 11:51 UTC, Yamaguchi commented on javascript/GettingStarted-ja.md
> +初めに以下のシンプルなサーバプログラムを `index.js` というファイル名で作成しサーバの起動を確認しましょう。
サーバなのかサーバーなのかドキュメント内で統一しましょう。

2021-07-28 11:51 UTC, Yamaguchi commented on javascript/GettingStarted-ja.md
> +`getuserInfo` API の詳細は [API ドキュメント](https://doc.api.tapyrus.chaintope.com/#operation/getUserInfo) を参照してください。
getuserInfo => getUserInfo

2021-07-28 11:51 UTC, Yamaguchi commented on javascript/GettingStarted-ja.md
> +必要なモジュールを読み込みます。
この一文の意味が不明です。具体的に何かする必要がありますか？

2021-07-28 11:51 UTC, Yamaguchi commented on javascript/GettingStarted-ja.md
> +// OpenID Connect client credentials. Modify for your own environment.
2.1のコードはコメントが日本語でここは英語なので、どちらかに統一すべきだと思います。

2021-07-28 11:51 UTC, Yamaguchi commented on javascript/GettingStarted-ja.md
> +`getAddress` API を利用してアドレスを生成します。 成功するとサーバーを起動しているコンソールにアドレスが出力されます。
createAddressでは?

2021-07-28 11:51 UTC, Yamaguchi commented on javascript/GettingStarted-ja.md
> +`getAddress` API を利用してアドレスを生成します。 成功するとサーバーを起動しているコンソールにアドレスが出力されます。
サーバーを起動して認証を行なっただけでは、コンソールには何も出力されません。
"成功するとサーバーを起動しているコンソールにアドレスが出力されます。"の文言は削除して良いと思います。

2021-07-28 11:51 UTC, Yamaguchi commented on javascript/GettingStarted-ja.md
> +### 4.2. アドレス作成アクションを追加する
4.2ではなく、4.1では？

2021-07-28 11:51 UTC, Yamaguchi commented on javascript/GettingStarted-ja.md
> +      console.log(JSON.stringify(data));
細かい話ですが、JSON.stringifyせずにdataをそのまま出力しても良いかと思います。
現状だと、

```
"\"1GmqexEwDZWWcZz6EzSQi8GK5chqeTdQ1Y\""
```

のように"が余計に出力されているので。

2021-08-03 02:08 UTC, azuchi requested changes

2021-08-03 02:08 UTC, azuchi commented on javascript/GettingStarted-ja.md
> +ここでは Tapyrus API を利用した Javascript のウェブアプリケーション開発の始め方について解説をします。 前提として Tapyrus ブロックチェーンや Tapyrus API の概要への理解が必要です。
```suggestion
ここでは Tapyrus API を利用した JavaScript のウェブアプリケーション開発の始め方について解説をします。 前提として Tapyrus ブロックチェーンや Tapyrus API の概要への理解が必要です。
```

2021-08-03 02:08 UTC, azuchi commented on javascript/GettingStarted-ja.md
> +Javascript を使ったウェブアプリケーションの構築を通して、ゴールの達成を目指します。
```suggestion
JavaScript を使ったウェブアプリケーションの構築を通して、ゴールの達成を目指します。
```

2021-08-03 02:08 UTC, azuchi commented on javascript/GettingStarted-ja.md
> +* [Testnet Explorer](https://testnet-explorer.tapyrus.dev.chaintope.com/blocks)
```suggestion
* [Testnet Explorer](https://testnet-explorer.tapyrus.dev.chaintope.com)
```

2021-08-03 02:08 UTC, azuchi commented on javascript/GettingStarted-ja.md
> +そのため上で入手したアクセストークン１つに付き１つの Tapyrus API ユーザーが必要です。
OpenID Providerの１ユーザーにつき、Tapyrus API １ユーザーの関係の方が良いかと思いました。

2021-08-03 02:08 UTC, azuchi commented on javascript/GettingStarted-ja.md
> +TPC が入っていませんので、送金をすることが出来ません。 そこで、アドレスを生成し、testnet のファーセットから資金を入手します。
```suggestion
TPC が入っていませんので、送金をすることが出来ません。 そこで、アドレスを生成し、testnet のfaucetから資金を入手します。
```

2021-08-03 02:08 UTC, azuchi commented on javascript/GettingStarted-ja.md
> +[ファーセット](https://testnet-faucet.tapyrus.dev.chaintope.com) へアクセスし、「Input your address」に作成したアドレスを入力してください。
```suggestion
[faucet](https://testnet-faucet.tapyrus.dev.chaintope.com) へアクセスし、「Input your address」に作成したアドレスを入力してください。
```

2021-08-03 02:08 UTC, azuchi commented on javascript/GettingStarted-ja.md
> +最後に TPC を送金してみます。 ファーセットには返却用のアドレスがありますので、そこあてに送金をすることにします。
```suggestion
最後に TPC を送金してみます。 faucetには返却用のアドレスがありますので、そこあてに送金をすることにします。
```

2021-08-03 02:08 UTC, azuchi commented on javascript/GettingStarted-ja.md
> +`to address` には、ファーセットの 「Return Address」からコピーしたアドレスを入力します。
```suggestion
`to address` には、faucetの 「Return Address」からコピーしたアドレスを入力します。
```

2021-08-03 02:08 UTC, azuchi commented on javascript/GettingStarted-ja.md
> +中段には、送金元のアドレスから送金先のアドレスへいくらずつ送られたかが表示されています。 左の送金元のアドレスは、ファーセットから受け取るときに使った自分のアドレスです。 右には送金先のアドレスがあり、上の 0.0001 TPC
```suggestion
中段には、送金元のアドレスから送金先のアドレスへいくらずつ送られたかが表示されています。 左の送金元のアドレスは、faucetから受け取るときに使った自分のアドレスです。 右には送金先のアドレスがあり、上の 0.0001 TPC
```

2021-08-03 02:08 UTC, azuchi commented on javascript/GettingStarted-ja.md
> +を受け取っているのがファーセットの返金用アドレスです。 その下はお釣り用のアドレスで、送金処理の際に内部で新しく生成されたものになります。
```suggestion
を受け取っているのがfaucetの返金用アドレスです。 その下はお釣り用のアドレスで、送金処理の際に内部で新しく生成されたものになります。
```

2021-08-03 02:08 UTC, azuchi commented on javascript/GettingStarted-ja.md
> +今回はテストネットを例に使っていますので、テストネットのファーセットからコインを手に入れます。 テストネット以外のネットワークを利用する場合は、その Tapyrus チェーンを運営しているフェデレーションの案内を確認してください。
```suggestion
今回はテストネットを例に使っていますので、テストネットのfaucetからコインを手に入れます。 テストネット以外のネットワークを利用する場合は、その Tapyrus チェーンを運営しているフェデレーションの案内を確認してください。
```

2021-09-07 04:47 UTC, rantan commented on javascript/GettingStarted-ja.md
> +初めに以下のシンプルなサーバプログラムを `index.js` というファイル名で作成しサーバの起動を確認しましょう。
サーバーで統一します。

2021-09-07 04:48 UTC, rantan commented on javascript/GettingStarted-ja.md
> +// OpenID Connect client credentials. Modify for your own environment.
日本語で統一します

2021-09-07 04:54 UTC, rantan commented on javascript/GettingStarted-ja.md
> +初めに以下のシンプルなサーバプログラムを `index.js` というファイル名で作成しサーバの起動を確認しましょう。
fix a09cbe4610b7ed16cb5187e359e2e18ff728e4fc

2021-09-07 05:01 UTC, rantan commented on javascript/GettingStarted-ja.md
> +必要なモジュールを読み込みます。
削除しました at b9bd52e7430353bcae5dd9efc3e7bd7a4a144493

2021-09-07 05:03 UTC, rantan commented on javascript/GettingStarted-ja.md
> +// OpenID Connect client credentials. Modify for your own environment.
fixed at e2824dd0302bc71e041747aadf21622f6ed78d01

2021-09-07 05:14 UTC, rantan commented on javascript/GettingStarted-ja.md
> +そのため上で入手したアクセストークン１つに付き１つの Tapyrus API ユーザーが必要です。
@azuchi 
ずいぶん前のコメントへの返信で恐縮ですが、「アクセストークン１つに付き１つの Tapyrus API ユーザー」と「OpenID Providerの１ユーザーにつき、Tapyrus API １ユーザー」は同じことを言っていると思うのですが、いかがでしょう？

それとも言い方の問題ですか？

2021-09-07 05:15 UTC, rantan commented on javascript/GettingStarted-ja.md
> +### 4.2. アドレス作成アクションを追加する
fixed at 3f07f86f5a9e77febb630ed0935e13d28e183e7c

2021-09-07 05:16 UTC, azuchi commented on javascript/GettingStarted-ja.md
> +そのため上で入手したアクセストークン１つに付き１つの Tapyrus API ユーザーが必要です。
OKです。

2021-09-07 05:38 UTC, rantan commented on javascript/GettingStarted-ja.md
> +      console.log(JSON.stringify(data));
fixed at eb53747efb6e371d893b41a9fbbc34f704564d0d

2021-09-07 05:41 UTC, rantan commented on javascript/GettingStarted-ja.md
> +`getAddress` API を利用してアドレスを生成します。 成功するとサーバーを起動しているコンソールにアドレスが出力されます。
ここは処理内容の説明の文章で、 `/create_address` を実行したときに、アドレスがコンソールに表示されることを説明しています。

` このアクションの実行に成功するとサーバーを起動しているコンソールにアドレスが出力されます。` のように書き足しておきます。

2021-09-07 05:44 UTC, rantan commented on javascript/GettingStarted-ja.md
> +`getAddress` API を利用してアドレスを生成します。 成功するとサーバーを起動しているコンソールにアドレスが出力されます。
fixed at b01c7834ac0788aa685cfa8454b3658d69404270

2021-09-07 05:45 UTC, rantan commented on javascript/GettingStarted-ja.md
> +`getAddress` API を利用してアドレスを生成します。 成功するとサーバーを起動しているコンソールにアドレスが出力されます。
fixed at b01c7834ac0788aa685cfa8454b3658d69404270

2021-09-07 05:46 UTC, rantan commented on javascript/GettingStarted-ja.md
> +`getuserInfo` API の詳細は [API ドキュメント](https://doc.api.tapyrus.chaintope.com/#operation/getUserInfo) を参照してください。
fixed at e038783eb9e2c505d86fe24e28894c83cdf79767

2021-09-07 05:49 UTC, rantan commented
時間空いてしまって申し訳ないですが、ご指摘いただいていた点についてひと通り修正しました。

2021-09-07 06:26 UTC, azuchi approved these changes

2021-09-07 09:14 UTC, merged