OAuth2ベースの認証を実装
chaintope/tapyrus-api-client-examples pull request #9
Opened 2022-07-18 16:25 UTC by Yamaguchi

https://github.com/chaintope/tapyrus-api/issues/116
に対応して、外部OPを使用する認証から、TapyruAPIのOAuth2ベースの認証に変更しました。

2022-07-25 05:13 UTC, Yamaguchi commented
GettingStarted-ja.mdも修正します。

2022-10-11 08:42 UTC, rantan requested changes

2022-10-11 08:42 UTC, rantan commented on javascript/example-app/index.js
>  });
state パラメーターが認証リクエスト発行時に渡した値と一致するか検証する必要があります。
https://openid-foundation-japan.github.io/rfc6749.ja.html#CSRF

2022-10-19 06:11 UTC, Yamaguchi commented
#10 がこのPRを含む形で実装しているため、このPRは閉じます。

2022-10-19 06:11 UTC, closed without merging